// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DbsCassandraProto.proto

package com.example.protobuf;

public final class DbsCassandraProto {
  private DbsCassandraProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultOfQueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResultOfQuery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否有错0：正常；1：查询错误
     * </pre>
     *
     * <code>int32 error = 1;</code>
     * @return The error.
     */
    int getError();

    /**
     * <pre>
     *错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <pre>
     *错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    int getResultCount();
    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    boolean containsResult(
        long key);
    /**
     * Use {@link #getResultMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, DbsCassandraProto.Value>
    getResult();
    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    java.util.Map<java.lang.Long, DbsCassandraProto.Value>
    getResultMap();
    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    /* nullable */
DbsCassandraProto.Value getResultOrDefault(
        long key,
        /* nullable */
DbsCassandraProto.Value defaultValue);
    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    DbsCassandraProto.Value getResultOrThrow(
        long key);
  }
  /**
   * <pre>
   *时间及对应值封装结果对应：queryExample，queryFull，queryVary
   * </pre>
   *
   * Protobuf type {@code ResultOfQuery}
   */
  public static final class ResultOfQuery extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResultOfQuery)
      ResultOfQueryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResultOfQuery.newBuilder() to construct.
    private ResultOfQuery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultOfQuery() {
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResultOfQuery();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_ResultOfQuery_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetResult();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_ResultOfQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DbsCassandraProto.ResultOfQuery.class, DbsCassandraProto.ResultOfQuery.Builder.class);
    }

    public static final int ERROR_FIELD_NUMBER = 1;
    private int error_ = 0;
    /**
     * <pre>
     *是否有错0：正常；1：查询错误
     * </pre>
     *
     * <code>int32 error = 1;</code>
     * @return The error.
     */
    @java.lang.Override
    public int getError() {
      return error_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object msg_ = "";
    /**
     * <pre>
     *错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *错误信息
     * </pre>
     *
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private static final class ResultDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Long, DbsCassandraProto.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Long, DbsCassandraProto.Value>newDefaultInstance(
                      internal_static_ResultOfQuery_ResultEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  DbsCassandraProto.Value.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Long, DbsCassandraProto.Value> result_;
    private com.google.protobuf.MapField<java.lang.Long, DbsCassandraProto.Value>
    internalGetResult() {
      if (result_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResultDefaultEntryHolder.defaultEntry);
      }
      return result_;
    }
    public int getResultCount() {
      return internalGetResult().getMap().size();
    }
    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    @java.lang.Override
    public boolean containsResult(
        long key) {
      
      return internalGetResult().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResultMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, DbsCassandraProto.Value> getResult() {
      return getResultMap();
    }
    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Long, DbsCassandraProto.Value> getResultMap() {
      return internalGetResult().getMap();
    }
    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
DbsCassandraProto.Value getResultOrDefault(
        long key,
        /* nullable */
DbsCassandraProto.Value defaultValue) {
      
      java.util.Map<java.lang.Long, DbsCassandraProto.Value> map =
          internalGetResult().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
     * </pre>
     *
     * <code>map&lt;int64, .Value&gt; result = 3;</code>
     */
    @java.lang.Override
    public DbsCassandraProto.Value getResultOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, DbsCassandraProto.Value> map =
          internalGetResult().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (error_ != 0) {
        output.writeInt32(1, error_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetResult(),
          ResultDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (error_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, error_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      for (java.util.Map.Entry<java.lang.Long, DbsCassandraProto.Value> entry
           : internalGetResult().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Long, DbsCassandraProto.Value>
        result__ = ResultDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, result__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DbsCassandraProto.ResultOfQuery)) {
        return super.equals(obj);
      }
      DbsCassandraProto.ResultOfQuery other = (DbsCassandraProto.ResultOfQuery) obj;

      if (getError()
          != other.getError()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!internalGetResult().equals(
          other.internalGetResult())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (!internalGetResult().getMap().isEmpty()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetResult().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DbsCassandraProto.ResultOfQuery parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DbsCassandraProto.ResultOfQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DbsCassandraProto.ResultOfQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DbsCassandraProto.ResultOfQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DbsCassandraProto.ResultOfQuery prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *时间及对应值封装结果对应：queryExample，queryFull，queryVary
     * </pre>
     *
     * Protobuf type {@code ResultOfQuery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResultOfQuery)
        DbsCassandraProto.ResultOfQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_ResultOfQuery_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_ResultOfQuery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DbsCassandraProto.ResultOfQuery.class, DbsCassandraProto.ResultOfQuery.Builder.class);
      }

      // Construct using com.example.protobuf.proto.DbsCassandraProto.ResultOfQuery.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        error_ = 0;
        msg_ = "";
        internalGetMutableResult().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_ResultOfQuery_descriptor;
      }

      @java.lang.Override
      public DbsCassandraProto.ResultOfQuery getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public DbsCassandraProto.ResultOfQuery build() {
        DbsCassandraProto.ResultOfQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DbsCassandraProto.ResultOfQuery buildPartial() {
        DbsCassandraProto.ResultOfQuery result = new DbsCassandraProto.ResultOfQuery(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(DbsCassandraProto.ResultOfQuery result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.error_ = error_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msg_ = msg_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.result_ = internalGetResult();
          result.result_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DbsCassandraProto.ResultOfQuery) {
          return mergeFrom((DbsCassandraProto.ResultOfQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DbsCassandraProto.ResultOfQuery other) {
        if (other == getDefaultInstance()) return this;
        if (other.getError() != 0) {
          setError(other.getError());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        internalGetMutableResult().mergeFrom(
            other.internalGetResult());
        bitField0_ |= 0x00000004;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                error_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                msg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.Long, DbsCassandraProto.Value>
                result__ = input.readMessage(
                    ResultDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableResult().getMutableMap().put(
                    result__.getKey(), result__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int error_ ;
      /**
       * <pre>
       *是否有错0：正常；1：查询错误
       * </pre>
       *
       * <code>int32 error = 1;</code>
       * @return The error.
       */
      @java.lang.Override
      public int getError() {
        return error_;
      }
      /**
       * <pre>
       *是否有错0：正常；1：查询错误
       * </pre>
       *
       * <code>int32 error = 1;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(int value) {
        
        error_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否有错0：正常；1：查询错误
       * </pre>
       *
       * <code>int32 error = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        msg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        msg_ = getDefaultInstance().getMsg();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息
       * </pre>
       *
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        msg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Long, DbsCassandraProto.Value> result_;
      private com.google.protobuf.MapField<java.lang.Long, DbsCassandraProto.Value>
          internalGetResult() {
        if (result_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ResultDefaultEntryHolder.defaultEntry);
        }
        return result_;
      }
      private com.google.protobuf.MapField<java.lang.Long, DbsCassandraProto.Value>
          internalGetMutableResult() {
        if (result_ == null) {
          result_ = com.google.protobuf.MapField.newMapField(
              ResultDefaultEntryHolder.defaultEntry);
        }
        if (!result_.isMutable()) {
          result_ = result_.copy();
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return result_;
      }
      public int getResultCount() {
        return internalGetResult().getMap().size();
      }
      /**
       * <pre>
       *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
       * </pre>
       *
       * <code>map&lt;int64, .Value&gt; result = 3;</code>
       */
      @java.lang.Override
      public boolean containsResult(
          long key) {
        
        return internalGetResult().getMap().containsKey(key);
      }
      /**
       * Use {@link #getResultMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, DbsCassandraProto.Value> getResult() {
        return getResultMap();
      }
      /**
       * <pre>
       *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
       * </pre>
       *
       * <code>map&lt;int64, .Value&gt; result = 3;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Long, DbsCassandraProto.Value> getResultMap() {
        return internalGetResult().getMap();
      }
      /**
       * <pre>
       *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
       * </pre>
       *
       * <code>map&lt;int64, .Value&gt; result = 3;</code>
       */
      @java.lang.Override
      public /* nullable */
DbsCassandraProto.Value getResultOrDefault(
          long key,
          /* nullable */
DbsCassandraProto.Value defaultValue) {
        
        java.util.Map<java.lang.Long, DbsCassandraProto.Value> map =
            internalGetResult().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
       * </pre>
       *
       * <code>map&lt;int64, .Value&gt; result = 3;</code>
       */
      @java.lang.Override
      public DbsCassandraProto.Value getResultOrThrow(
          long key) {
        
        java.util.Map<java.lang.Long, DbsCassandraProto.Value> map =
            internalGetResult().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableResult().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
       * </pre>
       *
       * <code>map&lt;int64, .Value&gt; result = 3;</code>
       */
      public Builder removeResult(
          long key) {
        
        internalGetMutableResult().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, DbsCassandraProto.Value>
          getMutableResult() {
        bitField0_ |= 0x00000004;
        return internalGetMutableResult().getMutableMap();
      }
      /**
       * <pre>
       *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
       * </pre>
       *
       * <code>map&lt;int64, .Value&gt; result = 3;</code>
       */
      public Builder putResult(
          long key,
          DbsCassandraProto.Value value) {
        
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableResult().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *由有序Map（时间，值）包装的一组数据，键表示对应分辨率的位置，值是采样处的值 。     KEY:time ;VALUE:value
       * </pre>
       *
       * <code>map&lt;int64, .Value&gt; result = 3;</code>
       */
      public Builder putAllResult(
          java.util.Map<java.lang.Long, DbsCassandraProto.Value> values) {
        internalGetMutableResult().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResultOfQuery)
    }

    // @@protoc_insertion_point(class_scope:ResultOfQuery)
    private static final DbsCassandraProto.ResultOfQuery DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DbsCassandraProto.ResultOfQuery();
    }

    public static DbsCassandraProto.ResultOfQuery getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResultOfQuery>
        PARSER = new com.google.protobuf.AbstractParser<ResultOfQuery>() {
      @java.lang.Override
      public ResultOfQuery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResultOfQuery> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResultOfQuery> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DbsCassandraProto.ResultOfQuery getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Value)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *数据类型 0：Double ;1：Long；
     * </pre>
     *
     * <code>int32 dType = 1;</code>
     * @return The dType.
     */
    int getDType();

    /**
     * <pre>
     *数据类型为0时的工程值
     * </pre>
     *
     * <code>double dValue = 2;</code>
     * @return The dValue.
     */
    double getDValue();

    /**
     * <pre>
     *数据类型为1时的工程值
     * </pre>
     *
     * <code>int64 lValue = 3;</code>
     * @return The lValue.
     */
    long getLValue();

    /**
     * <pre>
     *是否为空
     * </pre>
     *
     * <code>bool isNull = 4;</code>
     * @return The isNull.
     */
    boolean getIsNull();
  }
  /**
   * <pre>
   *单工程值的容器
   * </pre>
   *
   * Protobuf type {@code Value}
   */
  public static final class Value extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Value)
      ValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Value.newBuilder() to construct.
    private Value(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Value() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Value();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_Value_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DbsCassandraProto.Value.class, DbsCassandraProto.Value.Builder.class);
    }

    public static final int DTYPE_FIELD_NUMBER = 1;
    private int dType_ = 0;
    /**
     * <pre>
     *数据类型 0：Double ;1：Long；
     * </pre>
     *
     * <code>int32 dType = 1;</code>
     * @return The dType.
     */
    @java.lang.Override
    public int getDType() {
      return dType_;
    }

    public static final int DVALUE_FIELD_NUMBER = 2;
    private double dValue_ = 0D;
    /**
     * <pre>
     *数据类型为0时的工程值
     * </pre>
     *
     * <code>double dValue = 2;</code>
     * @return The dValue.
     */
    @java.lang.Override
    public double getDValue() {
      return dValue_;
    }

    public static final int LVALUE_FIELD_NUMBER = 3;
    private long lValue_ = 0L;
    /**
     * <pre>
     *数据类型为1时的工程值
     * </pre>
     *
     * <code>int64 lValue = 3;</code>
     * @return The lValue.
     */
    @java.lang.Override
    public long getLValue() {
      return lValue_;
    }

    public static final int ISNULL_FIELD_NUMBER = 4;
    private boolean isNull_ = false;
    /**
     * <pre>
     *是否为空
     * </pre>
     *
     * <code>bool isNull = 4;</code>
     * @return The isNull.
     */
    @java.lang.Override
    public boolean getIsNull() {
      return isNull_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dType_ != 0) {
        output.writeInt32(1, dType_);
      }
      if (java.lang.Double.doubleToRawLongBits(dValue_) != 0) {
        output.writeDouble(2, dValue_);
      }
      if (lValue_ != 0L) {
        output.writeInt64(3, lValue_);
      }
      if (isNull_ != false) {
        output.writeBool(4, isNull_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dType_);
      }
      if (java.lang.Double.doubleToRawLongBits(dValue_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, dValue_);
      }
      if (lValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, lValue_);
      }
      if (isNull_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isNull_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DbsCassandraProto.Value)) {
        return super.equals(obj);
      }
      DbsCassandraProto.Value other = (DbsCassandraProto.Value) obj;

      if (getDType()
          != other.getDType()) return false;
      if (java.lang.Double.doubleToLongBits(getDValue())
          != java.lang.Double.doubleToLongBits(
              other.getDValue())) return false;
      if (getLValue()
          != other.getLValue()) return false;
      if (getIsNull()
          != other.getIsNull()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDType();
      hash = (37 * hash) + DVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDValue()));
      hash = (37 * hash) + LVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLValue());
      hash = (37 * hash) + ISNULL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsNull());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DbsCassandraProto.Value parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DbsCassandraProto.Value parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DbsCassandraProto.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DbsCassandraProto.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DbsCassandraProto.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DbsCassandraProto.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DbsCassandraProto.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DbsCassandraProto.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DbsCassandraProto.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DbsCassandraProto.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DbsCassandraProto.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DbsCassandraProto.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DbsCassandraProto.Value prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *单工程值的容器
     * </pre>
     *
     * Protobuf type {@code Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Value)
        DbsCassandraProto.ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_Value_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DbsCassandraProto.Value.class, DbsCassandraProto.Value.Builder.class);
      }

      // Construct using com.example.protobuf.proto.DbsCassandraProto.Value.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        dType_ = 0;
        dValue_ = 0D;
        lValue_ = 0L;
        isNull_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_Value_descriptor;
      }

      @java.lang.Override
      public DbsCassandraProto.Value getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public DbsCassandraProto.Value build() {
        DbsCassandraProto.Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DbsCassandraProto.Value buildPartial() {
        DbsCassandraProto.Value result = new DbsCassandraProto.Value(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(DbsCassandraProto.Value result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.dType_ = dType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dValue_ = dValue_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.lValue_ = lValue_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.isNull_ = isNull_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DbsCassandraProto.Value) {
          return mergeFrom((DbsCassandraProto.Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DbsCassandraProto.Value other) {
        if (other == getDefaultInstance()) return this;
        if (other.getDType() != 0) {
          setDType(other.getDType());
        }
        if (other.getDValue() != 0D) {
          setDValue(other.getDValue());
        }
        if (other.getLValue() != 0L) {
          setLValue(other.getLValue());
        }
        if (other.getIsNull() != false) {
          setIsNull(other.getIsNull());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                dType_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                dValue_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 24: {
                lValue_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                isNull_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int dType_ ;
      /**
       * <pre>
       *数据类型 0：Double ;1：Long；
       * </pre>
       *
       * <code>int32 dType = 1;</code>
       * @return The dType.
       */
      @java.lang.Override
      public int getDType() {
        return dType_;
      }
      /**
       * <pre>
       *数据类型 0：Double ;1：Long；
       * </pre>
       *
       * <code>int32 dType = 1;</code>
       * @param value The dType to set.
       * @return This builder for chaining.
       */
      public Builder setDType(int value) {
        
        dType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据类型 0：Double ;1：Long；
       * </pre>
       *
       * <code>int32 dType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dType_ = 0;
        onChanged();
        return this;
      }

      private double dValue_ ;
      /**
       * <pre>
       *数据类型为0时的工程值
       * </pre>
       *
       * <code>double dValue = 2;</code>
       * @return The dValue.
       */
      @java.lang.Override
      public double getDValue() {
        return dValue_;
      }
      /**
       * <pre>
       *数据类型为0时的工程值
       * </pre>
       *
       * <code>double dValue = 2;</code>
       * @param value The dValue to set.
       * @return This builder for chaining.
       */
      public Builder setDValue(double value) {
        
        dValue_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据类型为0时的工程值
       * </pre>
       *
       * <code>double dValue = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dValue_ = 0D;
        onChanged();
        return this;
      }

      private long lValue_ ;
      /**
       * <pre>
       *数据类型为1时的工程值
       * </pre>
       *
       * <code>int64 lValue = 3;</code>
       * @return The lValue.
       */
      @java.lang.Override
      public long getLValue() {
        return lValue_;
      }
      /**
       * <pre>
       *数据类型为1时的工程值
       * </pre>
       *
       * <code>int64 lValue = 3;</code>
       * @param value The lValue to set.
       * @return This builder for chaining.
       */
      public Builder setLValue(long value) {
        
        lValue_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据类型为1时的工程值
       * </pre>
       *
       * <code>int64 lValue = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lValue_ = 0L;
        onChanged();
        return this;
      }

      private boolean isNull_ ;
      /**
       * <pre>
       *是否为空
       * </pre>
       *
       * <code>bool isNull = 4;</code>
       * @return The isNull.
       */
      @java.lang.Override
      public boolean getIsNull() {
        return isNull_;
      }
      /**
       * <pre>
       *是否为空
       * </pre>
       *
       * <code>bool isNull = 4;</code>
       * @param value The isNull to set.
       * @return This builder for chaining.
       */
      public Builder setIsNull(boolean value) {
        
        isNull_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否为空
       * </pre>
       *
       * <code>bool isNull = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsNull() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isNull_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Value)
    }

    // @@protoc_insertion_point(class_scope:Value)
    private static final DbsCassandraProto.Value DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DbsCassandraProto.Value();
    }

    public static DbsCassandraProto.Value getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Value>
        PARSER = new com.google.protobuf.AbstractParser<Value>() {
      @java.lang.Override
      public Value parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Value> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Value> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DbsCassandraProto.Value getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultOfQuery_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResultOfQuery_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultOfQuery_ResultEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResultOfQuery_ResultEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Value_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Value_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027DbsCassandraProto.proto\"\216\001\n\rResultOfQu" +
      "ery\022\r\n\005error\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022*\n\006resul" +
      "t\030\003 \003(\0132\032.ResultOfQuery.ResultEntry\0325\n\013R" +
      "esultEntry\022\013\n\003key\030\001 \001(\003\022\025\n\005value\030\002 \001(\0132\006" +
      ".Value:\0028\001\"F\n\005Value\022\r\n\005dType\030\001 \001(\005\022\016\n\006dV" +
      "alue\030\002 \001(\001\022\016\n\006lValue\030\003 \001(\003\022\016\n\006isNull\030\004 \001" +
      "(\010B/\n\032com.example.protobuf.protoB\021DbsCas" +
      "sandraProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ResultOfQuery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResultOfQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResultOfQuery_descriptor,
        new java.lang.String[] { "Error", "Msg", "Result", });
    internal_static_ResultOfQuery_ResultEntry_descriptor =
      internal_static_ResultOfQuery_descriptor.getNestedTypes().get(0);
    internal_static_ResultOfQuery_ResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResultOfQuery_ResultEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Value_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Value_descriptor,
        new java.lang.String[] { "DType", "DValue", "LValue", "IsNull", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
